logging:
  level:
    org.springframework.web: debug
    org.mybatis.spring: debug
  config:
    classpath: logback-spring.xml

server:
  port: 8888

spring:
  profiles:
    active: dev

  mvc:
    view:
      prefix: /view/jsp/
      suffix: .jsp


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /



  jackson:
    date-format: yyyy-MM-dd HH.mm.ss
    time-zone: GMT+8

  datasource:
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
